### ISSUE TITLE
main fails tsc --noEmit: #1804's dead-export sweep stripped exports a test on another branch imports (pre-push blocks every push)

### ISSUE THREAD

**Issue by ahhrealmonster** [Intense-Visions/harness-engineering#1820]
## Symptom

`main` (`32a3b8cde`) fails `pnpm --filter @harness-engineering/cli typecheck`:

```
src/mcp/context-surface.test.ts(8,3): error TS2459: Module '"./context-surface"' declares 'agentsMdEntry' locally, but it is not exported.
src/mcp/context-surface.test.ts(9,3): error TS2459: ... 'hooksEntry' ...
src/mcp/context-surface.test.ts(10,3): error TS2459: ... 'skillTreeEntries' ...
src/mcp/context-surface.test.ts(132,30): error TS7006: Parameter 'e' implicitly has an 'any' type.
```

Reproduced on a clean checkout of `origin/main` with no local modifications.

Practical impact beyond the red: the repo's **pre-push hook runs typecheck**, so
this blocks *every* push from every branch, whatever it touches. That is how I
hit it — pushing an unrelated fix.

The fourth error is a consequence of the first three: with
`skillTreeEntries` unexported the array is untyped, so the `.find()` callback
loses its parameter type.

## Cause — a merge-order collision, not a bad change

Neither side was wrong on its own:

| | |
| --- | --- |
| `5f8d82ff1` (2026-09-01) | `test: cover comprehend helpers + mcp context-surface` — adds `context-surface.test.ts`, importing the three helpers |
| `a6a02e3b9` / #1804 (2026-09-03) | dead-export sweep — removes `export` from exactly those three |

`git diff a6a02e3b9^1 a6a02e3b9 -- packages/cli/src/mcp/context-surface.ts` is
three lines, each `-export function X(` → `+function X(`.

The sweep was **right by its own measure**: nothing under `src/` imports those
helpers, so they read as dead. The test that does import them was on a
different branch. Each PR was green when measured, and the breakage exists only
in the combination — so no PR-time check could have seen it, which is worth
noting separately from the fix.

## Fix

PR restores the three `export` keywords and adds a comment recording *why*
they are exported, so the next sweep does not remove them again — without that
note this recurs the next time the detector runs. 14 tests in
`context-surface.test.ts` go from "cannot compile" to passing.

The alternative — move the coverage to the public entry point and let the
helpers stay private — is cleaner but is a test rewrite, so it is not what a
red-main fix should do. Happy to follow up if you prefer that shape.

## Worth considering separately

A dead-export detector that measures `src/` but not `*.test.ts` will keep
producing this, and the failure lands on `main` rather than on the PR. Either
the sweep should count test imports as consumers, or its output should flag
"only consumer is a test" as a distinct category for a human to judge.
